services:
  ucugestion:
    container_name: ucugestion
    build:
      context: .
      dockerfile: Dockerfile
    image: ucugestion:latest
    volumes:
      - .:/usr/src/app
    ports:
      - "80:3000"
    restart: unless-stopped
